# Generated by Django 5.1.2 on 2024-10-27 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_alter_pedido_total_alter_producto_precio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='stock',
        ),
    ]
